dataroot = 'D:/kaggle/datasets/img_align_celeba'  # image dataroot
maskroot = 'D:/kaggle/datasets/mask/testing_mask_dataset'  # mask dataroot
batchSize = 1   # Need to be set to 1
fineSize = 256  # image size
input_nc = 3  # input channel size for first stage
input_nc_g = 6  # input channel size for second stage
output_nc = 3  # output channel size
ngf = 64  # inner channel
ndf = 64  # inner channel
which_model_netD = 'basic'  # patch discriminator
which_model_netF = 'feature'  # feature patch discriminator
which_model_netG = 'unet_csa'  # seconde stage network
which_model_netP = 'unet_256'  # first stage network
triple_weight = 1
name = 'CSA_inpainting'
n_layers_D = '3'  # network depth
gpu_ids = [0]
model = 'csa_net'
checkpoints_dir = './checkpoints'
norm = 'instance'
fixed_mask = 1
use_dropout = false
init_type = 'normal'
mask_type = 'center'
lambda_A = 100
threshold = 0.3125
stride = 1
shift_sz = 1  # size of feature patch
mask_thred = 1
bottleneck = 512
gp_lambda = 10.0
ncritic = 5
constrain = 'MSE'
strength = 1
init_gain = 0.02
cosis = 1
gan_type = 'lsgan'
gan_weight = 0.2
overlap = 4
skip = 0
display_freq = 1000
print_freq = 50
save_latest_freq = 5000
save_epoch_freq = 2
continue_train = false
epoch_count = 1
phase = 'train'
which_epoch = ''
niter = 20
niter_decay = 100
beta1 = 0.5
lr = 0.0002
lr_policy = 'lambda'
lr_decay_iters = 50
isTrain = true
save_dir = 'outputs'